name: testeflutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  device_info_plus: ^9.1.2
  url_launcher: ^6.2.5
  encrypt: ^5.0.3
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "icons/icon.png" 



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
